### ISSUE TITLE
Broken features & Improvements

### ISSUE THREAD

**Issue by wolfy1339** [idleberg/m8tro-bootstrap#14]
# Jumbotron
- [ ] `::selection` doesn't show up like you would expect with a background
- [ ] Links in the `.jumbotron` blend in with the background (Ref: #10)
- [ ] Hovering over button variants inside a `.jumbotron`  (Ref: wolfy1339/m8tro-bootstrap@7220cf769057ab68f3efb30df7acf8b5b94d14ed)
# Tables
- [ ] Hovering over a `<tr>` with `.fa` inside a `.table-hover` (Ref: #9)
# Iconography
- [ ] `.glyphicon`s receive no styling when `.fa` does (Ref: wolfy1339/m8tro-bootstrap@e59f67acf77d8e5ca59d6ed65e2d6bd6490007bf – Ignore `font-weight` change for `<strong>`
# Tooltips and Popovers
- [ ] Arrows (`.tooltip-arrow` & `.popover > .arrow`) should be hidden
# Progress Bars
- [ ] `.progress-bar` is not cross-platform (Currently WebKit only) (Ref: wolfy1339/m8tro-bootstrap@30cf0e90b13f37859f8acc92f96cd9a206434efc)
  - Use `90deg` instead of `0`
  - Use `linear-gradient` instead of `-webkit-linear-gradient`
- [ ] `.progress-striped .progress-bar` is deprecated use `.progress-bar-striped` instead (wolfy1339/m8tro-bootstrap@51c466868786c1710f2cd555ba77f7cfe6f59845 – Ignore `background-size` changes & changes made to `.progress`)
- [ ] Enable use of a label (Ref: http://getbootstrap.com/components/#progress-label)
  - [ ] Use Bootstrap default 20px height on `.progress` (Ref: wolfy1339/m8tro-bootstrap@51c466868786c1710f2cd555ba77f7cfe6f59845 – Ignore all changes not made to `.progress`)
# Text Emphasis Classes
- [ ] Make anchors in text emphasis classes inherit the color
# Buttons
- [x] Fix disabled state on buttons (Ref: wolfy133
  9/m8tro-bootstrap@9d5526ac6be19afda61c67af3e4df21debee30e3)
- [ ] Fix active state on buttons (Ref: wolfy1339/m8tro-bootstrap@2eebfe72aeb478c9236b34b7b3b72d7a71c407b3)
# LESS files
- [ ] Vendor prefixes are used instead of the unprefixed version
- [ ] `@headings-font-family` should be set to inherit (default Bootstrap value)
- `theme.less` :
  - [ ] Reorganize file into sections (Some base already exists for this)
  - [ ] Don't use nesting selector to create new classes (Ref: wolfy1339/m8tro-bootstrap@a6b1d0d699a3843ae261eee1fee77f91f5bf5bef)
- [ ] Change comments to use double slashes `//` so that they don't output to the generated CSS (Ref: wolfy1339/m8tro-bootstrap@e08904f627998af8b8db3443af9d24bac0319f7a)
- [ ] Use `.bg-variant` mixin for custom background variants
# Gulpfile
- [ ] JSHint the file (Ref:  wolfy1339/m8tro-bootstrap@af420d9a35f2b38484da08d3553aa9d640e6e00e)
- [ ] Use the same settings for `clean-css` as Bootstrap (Guide: https://github.com/less/less-plugin-clean-css#programmatic-usage)
- [ ] Add CSSComb (Ref: #11)
- [ ] Generate Sourcemaps (Ref: wolfy1339/m8tro-bootstrap@3ddebb8153517d5448898e48fd8e34068ac2dc08)
  - [ ] Remove `less-plugin-autoprefix` as it causes errors with sourcemaps (Ref: less/less-plugin-autoprefix#17) and use `gulp-autoprefixer` instead
  - [ ] Replace `less-plugin-clean-css` with `gulp-clean-css`
  - [ ] Specifically tell `gulp-sourcemaps` to add `.min` to the file extension for minified files (Ref: wolfy1339/m8tro-bootstrap@169f93a7d326d8d3c1796880e44feeed88856247)

**Comment by wolfy1339** [comment]
@idleberg Can you review these issues?
